# Generated by Django 5.2.1 on 2025-06-03 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_tao', models.DateTimeField(auto_now_add=True)),
                ('duong_dan', models.FileField(upload_to='backups/')),
                ('Kich_Thuoc', models.PositiveIntegerField()),
                ('Note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_GV', models.CharField(max_length=20, unique=True)),
                ('Ho_Ten', models.CharField(max_length=100)),
                ('Gioi_tinh', models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ')], max_length=10)),
                ('SDT', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Sinh_nhat', models.DateField()),
                ('Dia_chi', models.TextField()),
                ('Chu_Nhiem', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_mon_hoc', models.CharField(max_length=20, unique=True)),
                ('Ten_Mon', models.CharField(max_length=100)),
                ('He_So', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten_lop_hoc', models.CharField(max_length=50)),
                ('Khoi', models.CharField(max_length=10)),
                ('Nien_Khoa', models.CharField(max_length=20)),
                ('Si_So', models.IntegerField()),
                ('Tg_Tao', models.DateTimeField(auto_now_add=True)),
                ('Tg_cap_Nhat', models.DateTimeField(auto_now=True)),
                ('GV_Chu_Nhiem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_chu_nhiem', to='analyst.giaovien')),
            ],
        ),
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_HS', models.CharField(max_length=20, unique=True)),
                ('Ngay_sinh', models.DateField()),
                ('Gioi_Tinh', models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ')], max_length=10)),
                ('Dia_chi', models.TextField()),
                ('So_dt_bo_me', models.CharField(max_length=15)),
                ('Ngay_nhap_hoc', models.DateField()),
                ('Lop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyst.lophoc')),
            ],
        ),
        migrations.AddField(
            model_name='giaovien',
            name='Day_lop',
            field=models.ManyToManyField(blank=True, to='analyst.lophoc'),
        ),
        migrations.CreateModel(
            name='LsChuyenLop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay_bat_dau_hoc', models.DateField()),
                ('Ngay_ket_thuc_hoc', models.DateField(blank=True, null=True)),
                ('HS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.hocsinh')),
                ('Lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.lophoc')),
            ],
        ),
        migrations.CreateModel(
            name='LsLenLop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay_len_lop', models.DateField()),
                ('HS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.hocsinh')),
                ('Lop_cu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_cu', to='analyst.lophoc')),
                ('Lop_moi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_moi', to='analyst.lophoc')),
            ],
        ),
        migrations.CreateModel(
            name='DiemSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loai_Diem', models.CharField(choices=[('thuongxuyen', 'Thường xuyên'), ('giuaky', 'Giữa kỳ'), ('cuoiky', 'Cuối kỳ')], max_length=20)),
                ('Diem_so', models.FloatField()),
                ('Ngay_nhap', models.DateField(auto_now_add=True)),
                ('GV', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyst.giaovien')),
                ('HS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.hocsinh')),
                ('Mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.monhoc')),
            ],
        ),
        migrations.CreateModel(
            name='PhanCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.giaovien')),
                ('Lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.lophoc')),
                ('Mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.monhoc')),
            ],
        ),
        migrations.CreateModel(
            name='ThoiGianBieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ngay', models.CharField(choices=[('thu2', 'Thứ 2'), ('thu3', 'Thứ 3'), ('thu4', 'Thứ 4'), ('thu5', 'Thứ 5'), ('thu6', 'Thứ 6'), ('thu7', 'Thứ 7')], max_length=10)),
                ('Tiet', models.IntegerField()),
                ('GV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.giaovien')),
                ('Lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.lophoc')),
                ('Mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.monhoc')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hoc_sinh', models.BooleanField(default=False)),
                ('is_giao_vien', models.BooleanField(default=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('lan_cuoi_dang_nhap', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hocsinh',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyst.userprofile'),
        ),
        migrations.CreateModel(
            name='HoatDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanh_dong', models.TextField()),
                ('Thoi_Gian', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyst.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='giaovien',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyst.userprofile'),
        ),
    ]
